# Change these first
owner: rouilj # Your GitHub username
repo: RoundupAssets # Your Github repository name

# Add your sites here
sites:
  - name: Main
    url: https://www.roundup-tracker.org
  - name: Tracker
    url: https://issues.roundup-tracker.org/
  - name: Wiki
    url: https://wiki.roundup-tracker.org
  - name: Distribution (pypi)
    url: https://pypi.org/project/roundup/
  - name: Roundup-users mailing list
    url: https://sourceforge.net/p/roundup/mailman/roundup-users/
  - name: Fossil based IRC Log
    url: https://rouilj.dynamic-dns.net/fossil/roundup_irc_logs/doc/trunk/log/roundup/
  - name: GitHub based IRC Log
    url: https://github.com/rouilj/test 
  - name: Mercurial Repo (sourceforge)
    url: https://sourceforge.net/p/roundup/code/ci/tip/tree/CHANGES.txt
  - name: Unofficial Github Mirror
    url: https://github.com/roundup-tracker/roundup
  - name: Travis CI
    url: https://travis-ci.com/github/roundup-tracker/roundup
  - name: CodeCov
    url: https://app.codecov.io/gh/roundup-tracker/roundup/
  - name: Coveralls
    url: https://coveralls.io/github/roundup-tracker/roundup

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /RoundupAssets
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: RoundupAssets
  introTitle: "Status of various assets used to manage/develop the Roundup Issue Tracker."
  introMessage: Monitor [Roundup Issue Tracker](https://www.roundup-tracker.org) assets using [**upptime running on github**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /RoundupAssets
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Roundup
      href: https://www.roundup-tracker.org/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
